(load "/home/vag/Documents/Games/FantasyGame/src/actors/actor-factories.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/background.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/exit-game.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/heading.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/knight-choice-option.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/load-game.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/mage-choice-option.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/menu-chooser.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/actors/new-game.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/graphics-management/actor.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/graphics-management/animation.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/graphics-management/inscription.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/graphics-management/utils.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/graphics-management/xtexture.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/opening-gui.scm")
(load "/home/vag/Documents/Games/FantasyGame/src/menu-creator.scm")

(load "/home/vag/Documents/Games/FantasyGame/src/main.scm")
